# Generated by Django 5.1.1 on 2024-11-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolio', '0002_portfolioasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='asset_portfolios', to='assets.asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to='portfolio.portfolio'),
        ),
    ]
